
wallpaper {
    monitor = DP-2
    path = /home/LukPer/Pictures/Backgrounds/vortex-black-hole-astronomy-3840x2160-5415.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/LukPer/Pictures/Backgrounds/vortex-black-hole-astronomy-3840x2160-5415.jpg
    fit_mode = cover
}