#!/bin/bash
if pgrep -x "ncmpcpp" > /dev/null; then
mpc toggle
else
hyprctl dispatch focusmonitor HDMI-A-1
    hyprctl dispatch workspace 5

hyprctl dispatch exec "[workspace 5; monitor HDMI-A-1] kitty zsh -is -c 'ncmpcpp; zsh'"
fi
